### ISSUE TITLE
make proposal for 2-layer menu nesting

### ISSUE THREAD

**Issue by bertdv** [biaslab/hugo-academic-group#37]
Make a proposal to nest the mennu w a submenu (just 1-layer of subnesting deep)

**Comment by ivan-bocharov** [comment]
This can be solved via standard Hugo tools:
```toml
[[menu.main]]
    name = "MSc projects"
    url = "#vacancies"
    parent = "recruitment"
```
